In [1]:
import eng_to_ipa
import pandas as pd
import numpy as np

In [2]:
#Loading data
data = pd.read_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/75kidsubset.csv')

# Making list with words from dataset
data['item_definition']
item_list = data['item_definition'].tolist()
len(item_list)

# New list with unique items
unique_items = set(item_list)
type(unique_items)

# Making sure it is a list (because of problems with set)
unique_items_list = sorted(unique_items)
print(unique_items_list)
type(unique_items_list)

['I', 'TV', 'a', 'about', 'above', 'after', 'airplane', 'all', 'alligator', 'am', 'an', 'and', 'animal', 'ankle', 'another', 'ant', 'any', 'apple', 'applesauce', 'are', 'arm', 'around', 'asleep', 'at', 'aunt', 'awake', 'away', 'baby', 'babysitter', 'back', 'backyard', 'bad', 'ball', 'balloon', 'banana', 'basement', 'basket', 'bat', 'bath', 'bathroom', 'bathtub', 'be', 'beach', 'beads', 'beans', 'bear', 'because', 'bed', 'bedroom', 'bee', 'before', 'behind', 'belt', 'bench', 'beside', 'better', 'bib', 'bicycle', 'big', 'bird', 'bite', 'black', 'blanket', 'block', 'blow', 'blue', 'boat', 'book', 'boots', 'bottle', 'bowl', 'box', 'boy', 'bread', 'break', 'breakfast', 'bring', 'broken', 'broom', 'brother', 'brown', 'brush', 'bubbles', 'bucket', 'bug', 'build', 'bump', 'bunny', 'bus', 'but', 'butter', 'butterfly', 'buttocks', 'button', 'buy', 'by', 'bye', 'cake', 'call', 'camera', 'camping', 'can', 'candy', 'car', 'careful', 'carrots', 'carry', 'cat', 'catch', 'cereal', 'chair', 'chalk', 'c

list

In [3]:
# Transforming words to phonetics
phonetic_items = [] #creating empty list

for word in unique_items_list: #looping through list of words 
    phonetic_representation = eng_to_ipa.convert(word) #converting words to phonetics
    phonetic_items.append(phonetic_representation) #appending words to list

print(phonetic_items)
type(phonetic_items) #check that it's a list

['aɪ', 'ˌtɛləˈvɪʒən', 'ə', 'əˈbaʊt', 'əˈbəv', 'ˈæftər', 'ˈɛrˌpleɪn', 'ɔl', 'ˈæləˌgeɪtər', 'æm', 'ən', 'ənd', 'ˈænəməl', 'ˈæŋkəl', 'əˈnəðər', 'ænt', 'ˈɛni', 'ˈæpəl', 'ˈæpəlˌsɔs', 'ər', 'ɑrm', 'əraʊnd', 'əsˈlip', 'æt', 'ɔnt', 'əˈweɪk', 'əˈweɪ', 'ˈbeɪbi', 'ˈbeɪbiˌsɪtər', 'bæk', 'ˈbæˌkjɑrd', 'bæd', 'bɔl', 'bəˈlun', 'bəˈnænə', 'ˈbeɪsmənt', 'ˈbæskət', 'bæt', 'bæθ', 'ˈbæθˌrum', 'ˈbæθtəb', 'bi', 'biʧ', 'bidz', 'binz', 'bɛr', 'bɪˈkəz', 'bɛd', 'ˈbɛˌdrum', 'bi', 'ˌbiˈfɔr', 'bɪˈhaɪnd', 'bɛlt', 'bɛnʧ', 'ˌbiˈsaɪd', 'ˈbɛtər', 'bɪb', 'ˈbaɪsɪkəl', 'bɪg', 'bərd', 'baɪt', 'blæk', 'ˈblæŋkɪt', 'blɑk', 'bloʊ', 'blu', 'boʊt', 'bʊk', 'buts', 'ˈbɑtəl', 'boʊl', 'bɑks', 'bɔɪ', 'brɛd', 'breɪk', 'ˈbrɛkfəst', 'brɪŋ', 'ˈbroʊkən', 'brum', 'ˈbrəðər', 'braʊn', 'brəʃ', 'ˈbəbəlz', 'ˈbəkɪt', 'bəg', 'bɪld', 'bəmp', 'ˈbəni', 'bəs', 'bət', 'ˈbətər', 'ˈbətərˌflaɪ', 'ˈbətəks', 'ˈbətən', 'baɪ', 'baɪ', 'baɪ', 'keɪk', 'kɔl', 'ˈkæmərə', 'ˈkæmpɪŋ', 'kən', 'ˈkændi', 'kɑr', 'ˈkɛrfəl', 'ˈkɛrəts', 'ˈkɛri', 'kæt', 'kæʧ', 'ˈsɪriəl', 'ʧɛr

list

In [4]:
# Making a dataframe with words and their phonetic transcriptions
phonetic_and_words = pd.DataFrame({'Items' : [unique_items_list],
                                'Phonetics' : [phonetic_items]},
                                columns=['Items','Phonetics'])

print(phonetic_and_words) #checking that the words match

                                               Items  \
0  [I, TV, a, about, above, after, airplane, all,...   

                                           Phonetics  
0  [aɪ, ˌtɛləˈvɪʒən, ə, əˈbaʊt, əˈbəv, ˈæftər, ˈɛ...  


In [5]:
# Creating a function to calculate levenshtein distance/edit distance
def levenshtein_distance(word1, word2):
    # Make sure word1 is shorter or equal in length to word2
    if len(word1) > len(word2):
        word1, word2 = word2, word1 #if word1 is bigger than word2, change the order to optimize and reduce iterations

    previous_row = range(len(word2) + 1)

    for i, c1 in enumerate(word1): #for index(indicates placement in word), character in first word 
        current_row = [i + 1]
        for j, c2 in enumerate(word2):
            insertions = previous_row[j + 1] + 1 #The distance if you were to insert a character into word1
            deletions = current_row[j] + 1 #The distance if you were to delete a character from word1
            substitutions = previous_row[j] + (c1 != c2) #The distance if you were to substitute one character in word1 with the corresponding character in word2
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row

    return previous_row[-1]

#Testing the function
levenshtein_distance("elf", "elephant")

6

In [6]:
# Create Matrix
phonetic_matrix = np.zeros((len(phonetic_items), len(phonetic_items)))

# Calculate Levenshtein distance for each pair of words
for i in range(len(phonetic_items)):
    for j in range(len(phonetic_items)):
        phonetic_matrix[i, j] = levenshtein_distance(phonetic_items[i], phonetic_items[j])

print(phonetic_matrix)

[[ 0. 10.  2. ...  6.  5.  2.]
 [10.  0. 10. ... 10.  8. 11.]
 [ 2. 10.  0. ...  5.  5.  2.]
 ...
 [ 6. 10.  5. ...  0.  4.  5.]
 [ 5.  8.  5. ...  4.  0.  5.]
 [ 2. 11.  2. ...  5.  5.  0.]]


In [7]:
# Create a DataFrame from the semantic distance matrix to look for errors/make sure that the output is correct
phonetic_df = pd.DataFrame(phonetic_matrix, columns=unique_items_list, index=unique_items_list)

# Print the DataFrame
print(phonetic_df)

# Save as csv
phonetic_df.to_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/phonetic_distance.csv')

             I    TV     a  about  above  after  airplane   all  alligator  \
I          0.0  10.0   2.0    5.0    5.0    6.0       8.0   2.0       10.0   
TV        10.0   0.0  10.0    9.0    8.0    9.0       9.0  10.0        8.0   
a          2.0  10.0   0.0    5.0    4.0    5.0       9.0   2.0       10.0   
about      5.0   9.0   5.0    0.0    3.0    6.0       9.0   6.0        9.0   
above      5.0   8.0   4.0    3.0    0.0    5.0       9.0   5.0        9.0   
...        ...   ...   ...    ...    ...    ...       ...   ...        ...   
yourself   8.0  11.0   8.0    8.0    8.0    7.0       7.0   6.0       10.0   
yucky      5.0  10.0   4.0    5.0    4.0    5.0       8.0   5.0        9.0   
zebra      6.0  10.0   5.0    6.0    5.0    5.0       8.0   6.0        9.0   
zipper     5.0   8.0   5.0    6.0    5.0    3.0       7.0   6.0        7.0   
zoo        2.0  11.0   2.0    6.0    5.0    6.0       9.0   2.0       11.0   

            am  ...   yes  yesterday  yogurt   you  your  yours