In [101]:
import eng_to_ipa
import pandas as pd
import enchant
import numpy as np

In [102]:
data = pd.read_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/75kidsubset.csv')

# Making list with words from dataset
data['item_definition']
item_list = data['item_definition'].tolist()
print(item_list)
len(item_list)

# New list with unique items
unique_items = set(item_list)

unique_items_list = list(unique_items)
print(unique_items_list)
type(unique_items_list)

['catch', 'chase', 'clap', 'climb', 'close', 'feed', 'find', 'finish', 'fit', 'fix', 'get', 'give', 'go', 'hate', 'have', 'hear', 'yes', 'bite', 'blow', 'break', 'bring', 'build', 'bump', 'buy', 'carry', 'people', 'person', 'police', 'sister', 'cook', 'cover', 'cry', 'cut', 'dance', 'draw', 'drive', 'drop', 'dump', 'eat', 'fall', 'nap', 'no', 'pattycake', 'peekaboo', 'please', 'shh', 'shopping', 'snack', 'yogurt', 'beads', 'belt', 'bib', 'boots', 'button', 'coat', 'diaper', 'dress', 'gloves', 'hat', 'jacket', 'jeans', 'mittens', 'necklace', 'pajamas', 'pants', 'scarf', 'shirt', 'shoe', 'shorts', 'slipper', 'sneaker', 'snowsuit', 'sock', 'sweater', 'tights', 'underpants', 'zipper', 'ankle', 'arm', 'buttocks', 'cheek', 'chin', 'ear', 'eye', 'face', 'finger', 'foot', 'hair', 'hand', 'head', 'knee', 'leg', 'lips', 'mouth', 'nose', 'penis', 'shoulder', 'toe', 'tongue', 'tooth', 'tummy', 'vagina', 'basket', 'blanket', 'bottle', 'bowl', 'box', 'broom', 'brush', 'bucket', 'camera', 'clock', 'c

list

In [103]:
phonetic_items = []

for word in unique_items_list:
    phonetic_representation = eng_to_ipa.convert(word)
    phonetic_items.append(phonetic_representation)

print(phonetic_items)
type(phonetic_items)

['spun', 'tɔɪ', 'weɪk', 'ˈɛləfənt', 'ni', 'haʊ', 'steɪ', 'kəp', 'ˈtaɪni', 'sɔlt', 'ʃɔrts', 'ˈʧɪrioʊs', 'gləvz', 'aɪ', 'ˈbroʊkən', 'ˈnæpkɪn', 'haɪ', 'ˈbɛtər', 'wərk', 'laɪən', 'ˈtɪʃu', 'si', 'snoʊ', 'ðɛn', 'ˈkɔfi', 'ˈtaɪgər', 'ˈbətər', 'tuθ', 'taɪts', 'pleɪt', 'wɑʃ', 'ˈhəri', 'dək', 'kɔrn', 'ˈhæmər', 'ˈstrɔˌbɛri', 'ˈprɛtzəl', 'hɛd', 'ˈwɔtər', 'peɪnt', 'ˈkrækər', 'mɑp', 'ˈmoʊtərˌsaɪkəl', 'fɪt', 'toʊ', 'ˈpeɪpər', 'bɑks', 'wʊd', 'pʊt', 'tɪ', 'faɪnd', 'vəˈnɪlə', 'sɪŋk', 'ˈʃɑpɪŋ', 'grin', 'ˈprɛzənt', 'draɪv', 'ɪt', 'laʊd', 'ɔf', 'ˈɛvəri', 'ˈkaʊˌbɔɪ', 'ʧeɪs', 'faɪn', 'rɛd', 'bɔl', 'təˈnaɪt', 'pænts', 'wɔʧ', 'fɪʃ', 'mun', 'haɪd', 'ˈwɪndi', 'flaʊər', 'ɪr', 'kʊk', 'ˈdaʊnˈtaʊn', 'ˈpərsən', 'ˈzibrə', 'snæk', 'bloʊ', 'meɪk', 'ˈjɛstərˌdeɪ', 'æt', 'ˈbɑtəl', 'ər', 'ˈlɑliˌpɑp', 'ʃu', 'sloʊ', 'ˈbeɪbi', 'wət', 'əˈbəv', 'piz', 'bɪld', 'ˈpɑpsɪkəl', 'ʤəræf', 'nɑk', 'bɪˈkəz', 'ˈreɪzɪn', 'pɔr', 'ˈbæskət', 'deɪ', 'hoʊld', 'kreɪɑn', 'ˈbrəðər', 'sɔft', 'haɪ', 'rɪˈfrɪʤərˌeɪtər', 'ˈjoʊgərt', 'ˈbəni', 'sup', 'ˈmɪtə

list

In [104]:
# Making a dataframe with words and their phonetic transcriptions
phonetic_and_words = pd.DataFrame({'Items' : [unique_items_list],
                                'Phonetics' : [phonetic_items]},
                                columns=['Items','Phonetics'])

print(phonetic_and_words)

                                               Items  \
0  [spoon, toy, wake, elephant, knee, how, stay, ...   

                                           Phonetics  
0  [spun, tɔɪ, weɪk, ˈɛləfənt, ni, haʊ, steɪ, kəp...  


In [105]:
def levenshtein_distance(word1, word2):
    # Make sure word1 is shorter or equal in length to word2
    if len(word1) > len(word2):
        word1, word2 = word2, word1

    previous_row = range(len(word2) + 1)

    for i, c1 in enumerate(word1):
        current_row = [i + 1]
        for j, c2 in enumerate(word2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row

    return previous_row[-1]

#Testing
levenshtein_distance("elf", "elephant")

6

In [106]:
# Create Matrix
phonetic_matrix = np.zeros((len(phonetic_items), len(phonetic_items)))

# Calculate Levenshtein distance for each pair of words
for i in range(len(phonetic_items)):
    for j in range(len(phonetic_items)):
        phonetic_matrix[i, j] = levenshtein_distance(phonetic_items[i], phonetic_items[j])


print(phonetic_matrix)

[[0. 4. 4. ... 3. 4. 5.]
 [4. 0. 3. ... 3. 3. 5.]
 [4. 3. 0. ... 4. 4. 6.]
 ...
 [3. 3. 4. ... 0. 1. 5.]
 [4. 3. 4. ... 1. 0. 6.]
 [5. 5. 6. ... 5. 6. 0.]]


In [107]:
# Create a DataFrame from the semantic distance matrix to look for errors/make sure that the output is correct
phonetic_df = pd.DataFrame(phonetic_matrix, columns=unique_items_list, index=unique_items_list)

# Print the DataFrame
print(phonetic_df)

# Save as csv
phonetic_df.to_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/phonetic_distance.csv')

          spoon  toy  wake  elephant  knee  how  stay  cup  tiny  salt  ...  \
spoon       0.0  4.0   4.0       7.0   4.0  4.0   3.0  4.0   5.0   3.0  ...   
toy         4.0  0.0   3.0       8.0   3.0  3.0   2.0  3.0   4.0   3.0  ...   
wake        4.0  3.0   0.0       8.0   4.0  4.0   3.0  4.0   5.0   4.0  ...   
elephant    7.0  8.0   8.0       0.0   7.0  8.0   8.0  7.0   6.0   6.0  ...   
knee        4.0  3.0   4.0       7.0   0.0  3.0   4.0  3.0   4.0   4.0  ...   
...         ...  ...   ...       ...   ...  ...   ...  ...   ...   ...  ...   
turtle      7.0  6.0   7.0       6.0   7.0  7.0   6.0  6.0   5.0   6.0  ...   
his         4.0  3.0   3.0       8.0   3.0  2.0   4.0  3.0   5.0   4.0  ...   
pull        3.0  3.0   4.0       7.0   3.0  3.0   4.0  3.0   6.0   3.0  ...   
owl         4.0  3.0   4.0       7.0   3.0  2.0   4.0  3.0   5.0   3.0  ...   
pizza       5.0  5.0   6.0       6.0   5.0  6.0   5.0  6.0   5.0   5.0  ...   

          and  helicopter  hat  cover  scissors  tu