In [12]:
import gensim
import gensim.downloader
import pandas as pd
from gensim.models import KeyedVectors
import numpy as np

In [13]:
word2vec = gensim.downloader.load('word2vec-google-news-300')
word2vec.most_similar("cat")

[('cats', 0.8099379539489746),
 ('dog', 0.7609457969665527),
 ('kitten', 0.7464984655380249),
 ('feline', 0.7326233983039856),
 ('beagle', 0.7150582671165466),
 ('puppy', 0.7075453400611877),
 ('pup', 0.6934291124343872),
 ('pet', 0.6891530752182007),
 ('felines', 0.6755931377410889),
 ('chihuahua', 0.6709762215614319)]

In [14]:
word2vec_twit = gensim.downloader.load('glove-twitter-25')
word2vec_twit.most_similar("cat")

[('dog', 0.9590820074081421),
 ('monkey', 0.9203580021858215),
 ('bear', 0.9143136739730835),
 ('pet', 0.9108032584190369),
 ('girl', 0.8880629539489746),
 ('horse', 0.8872726559638977),
 ('kitty', 0.8870542645454407),
 ('puppy', 0.886769711971283),
 ('hot', 0.886525571346283),
 ('lady', 0.8845518827438354)]

In [15]:
data = pd.read_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/75kidsubset.csv')

data['item_definition']
item_list = data['item_definition'].tolist()
print(item_list)
len(item_list)

# New list with unique items
unique_items = set(item_list)
len(unique_items)

#Checking type
type(unique_items)

#Type was set so I change it to list using sorted()
unique_items_list = sorted(unique_items)
type(unique_items_list)

['catch', 'chase', 'clap', 'clean', 'climb', 'close', 'feed', 'find', 'finish', 'fit', 'fix', 'get', 'give', 'go', 'hate', 'have', 'hear', 'yes', 'bite', 'blow', 'break', 'bring', 'build', 'bump', 'buy', 'carry', 'people', 'person', 'police', 'sister', 'cook', 'cover', 'cry', 'cut', 'dance', 'draw', 'drink', 'drive', 'drop', 'dry', 'dump', 'eat', 'fall', 'nap', 'no', 'pattycake', 'peekaboo', 'please', 'shh', 'shopping', 'snack', 'water', 'yogurt', 'beads', 'belt', 'bib', 'boots', 'button', 'coat', 'diaper', 'dress', 'gloves', 'hat', 'jacket', 'jeans', 'mittens', 'necklace', 'pajamas', 'pants', 'scarf', 'shirt', 'shoe', 'shorts', 'slipper', 'sneaker', 'snowsuit', 'sock', 'sweater', 'tights', 'underpants', 'zipper', 'ankle', 'arm', 'buttocks', 'cheek', 'chin', 'ear', 'eye', 'face', 'finger', 'foot', 'hair', 'hand', 'head', 'knee', 'leg', 'lips', 'mouth', 'nose', 'penis', 'shoulder', 'toe', 'tongue', 'tooth', 'tummy', 'vagina', 'basket', 'blanket', 'bottle', 'bowl', 'box', 'broom', 'brush

list

In [16]:
# With word2vec model
semantic_distances = np.zeros((len(unique_items_list), len(unique_items_list)))

for i in range(len(unique_items_list)):
    for j in range(len(unique_items_list)):
        if unique_items_list[i] in word2vec and unique_items_list[j] in word2vec:
            semantic_distances[i, j] = word2vec.similarity(unique_items_list[i], unique_items_list[j])


print(semantic_distances)


[[0.99999994 0.1241132  0.         ... 0.06008499 0.10607126 0.03853573]
 [0.1241132  1.         0.         ... 0.05873623 0.003545   0.07287459]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.06008499 0.05873623 0.         ... 1.         0.18545128 0.39437976]
 [0.10607126 0.003545   0.         ... 0.18545128 1.00000012 0.04806608]
 [0.03853573 0.07287459 0.         ... 0.39437976 0.04806608 1.        ]]


In [17]:
# Create a DataFrame from the semantic distance matrix to look for errors/make sure that the output is correct
semantic_distances_df = pd.DataFrame(semantic_distances, columns=unique_items_list, index=unique_items_list)

# Print the DataFrame
print(semantic_distances_df)

semantic_distances_df.to_csv('/Users/tildeidunsloth/Desktop/bachelor/Bachelor/Data/semantic_distances.csv')

                 I        TV    a     about     above     after  airplane  \
I         1.000000  0.124113  0.0  0.306293  0.076046  0.113879  0.144709   
TV        0.124113  1.000000  0.0  0.064889  0.013148  0.082636  0.092847   
a         0.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000   
about     0.306293  0.064889  0.0  1.000000  0.186163  0.275972  0.115180   
above     0.076046  0.013148  0.0  0.186163  1.000000  0.095952  0.071768   
...            ...       ...  ...       ...       ...       ...       ...   
yourself  0.454754  0.102539  0.0  0.113403  0.053718  0.064753  0.115407   
yucky     0.240613  0.023236  0.0  0.127019  0.072968  0.037225  0.117635   
zebra     0.060085  0.058736  0.0 -0.001360  0.044306  0.013362  0.107917   
zipper    0.106071  0.003545  0.0  0.016005  0.063274 -0.033462  0.187592   
zoo       0.038536  0.072875  0.0  0.076424 -0.016113  0.108045  0.097746   

               all  alligator        am  ...       yes  yesterday    yogurt

In [18]:
# Doing a little testing to see if things are right
word2vec.similarity("I", "TV")


0.1241132